- name: Scale out the cluster
  hosts: localhost  # Specify the target host from your Ansible inventory
  gather_facts: no
  collections:
    - vmware.vmware_rest
    - community.vmware
  vars_files:
    - vars_scaleout.yml
  tasks:

    - name: Get InfraEnv spec
      k8s_info:
        api_version: agent-install.openshift.io/v1beta1
        kind: InfraEnv
        namespace: "{{ namespace }}"
      register: InfraEnv

    - name: Extract isoDownloadURL from the InfraEnv Kubernetes object
      set_fact:
        iso_location: "{{ InfraEnv.resources[0].status.isoDownloadURL }}"

    - name: Get the number of  existing agents
      k8s_info:
        api_version: agent-install.openshift.io/v1beta1
        kind: Agent
        namespace: "{{ namespace }}"
      register: existing_agents


    - name: Find hosts with type VM
      set_fact:
        vm_hosts: "{{ ocpnodes | selectattr('type', 'equalto', 'VM') | list }}"



    - name: upload the iso file to DS
      include_tasks: upload-iso.yml
      when: vm_hosts | length > 0

    - name: attach ISO to VMs
      include_tasks: attach-cdrom.yml
      loop: "{{ ocpnodes }}"
      when:
        - item.type == 'VM'
      loop: "{{ ocpnodes }}"


    - name: Scale out with BMs
      include_tasks: attach-cdrom-bm.yml
      when:
        - item.type == 'BM'
      loop: "{{ ocpnodes }}"

    - name: approve workers
      include_tasks: scale-worker-approve-hosts.yml
