clusterName: 47m7s
namespace: 47m7s-deploy
baseDomain: dynamic.opentlc.com
#apiVIP: 10.10.10.1 ### required for integrated deployments
imageSetName: img4.13.5-x86-64-appsub
#ingressVIP: 10.10.10.2 required for integrated deployments
platformType: None
controlPlaneAgents: 3
workerAgents: 2
pullSecret: environments/w7t2z/pull-secret.json
sshPublicKey: |
  bastion public here

dnsServers:
  - 192.168.66.10
  - 10.2.192.12
  - 8.8.8.8
defaultGateway: 192.168.66.1
hosts:
  - hostName: control-plane-0
    nics:
      - nicName: ens192
        ipAddress: 192.168.66.11
        ports:
          - ens192
        macAddresses:
          ens192: 00:50:56:a2:ea:40
  - hostName: control-plane-1
    nics:
      - nicName: ens192
        ipAddress: 192.168.66.12
        ports:
          - ens192
        macAddresses:
          ens192: 00:50:56:a2:1f:29
  - hostName: control-plane-2
    nics:
      - nicName: ens192
        ipAddress: 192.168.66.13
        ports:
          - ens192
        macAddresses:
          ens192: 00:50:56:a2:8d:14

  - hostName: worker-0
    nics:
      - nicName: ens192
        ipAddress: 192.168.66.14
        ports:
          - ens192
        macAddresses:
          ens192: 00:50:56:a2:0c:4e

  - hostName: worker-1
    nics:
      - nicName: ens192
        ipAddress: 192.168.66.15
        ports:
          - ens192
        macAddresses:
          ens192: 00:50:56:a2:c0:31
  - hostName: worker-2
    nics:
      - nicName: bond0
        ipAddress: 192.168.66.16
        ports:
          - ens192
          - ens224
        macAddresses:
          ens192: 00:50:56:a2:15:4f
          ens224: 00:50:56:a2:bf:21
    bondType: 802.3ad  # or set it to active-backup as needed
